package org.example;
import java.sql.*;

import static org.example.Conexion.getConnection;

public class crearTabla {
    public static void crearTablas() {

        //definimos un create table para crear la tabla del departamento
        String sqlDep =  "CREATE TABLE departamento (" +
                         "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                         "nombre VARCHAR2(100))";

        //añadimos la columna departamento_id a la tabla empleado
        //usamos un ALTER TABLE y añadimos
        String sqlColumna = "ALTER TABLE empleado ADD departamento_id NUMBER";

        //declaramos la clave foránea que relaciona las tablas
        String sqlClaveFor = "ALTER TABLE empleado ADD CONSTRAINT fk_departamento " +
                             "FOREIGN KEY (departamento_id) REFERENCES departamento(id)";

        //hacemos el try y declaramos un Statemen
        //como no hay parámetros ? usamos Statement en lugar de PreparedStatement
        try (Connection conn = getConnection();
             Statement st = conn.createStatement()) {

            st.executeUpdate(sqlDep);
            System.out.println("Tabla DEPARTAMENTO creada.");

            st.executeUpdate(sqlColumna);
            System.out.println("Columna departamento_id añadida a EMPLEADO.");

            st.executeUpdate(sqlClaveFor);
            System.out.println("FK añadida correctamente.");

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    //ejecutamos el método
    public static void main(String[] args){
        crearTablas();
    }


}
